spring:
  application:
    name: ChangeEvent

  jpa:
    properties:
      hibernate:
        generate_statistics: false
        jdbc:
          batch_size: 5000
#        order_inserts: true
#        order_updates: true
#        order_deletes: true
  datasource:
    hikari:
      minimum-idle: 10
      maximum-pool-size: 10
      data-source-properties:
        reWriteBatchedInserts: true